require 'csv'
require File.expand_path('../config/environment', __dir__)

CSV.foreach('/home/vmaroudas/Downloads/pistons.csv', headers: true) do |row|
  Piston.create!(
    engine_maker: row['ENGINE MAKER'],
    piston_reference_number: row['PISTON REFERENCE NUMBER'],
    vehicle: row['VEHICLE'],
    vehicle_indexing: row['VEHICLE INDEXING'],
    model_year: row['MODEL YEAR'],
    engine_types: row['ENGINE TYPES'],
    cubic_displacement: row['CUBIC DISPLACEMENT'],
    fuel: row['FUEL'],
    compression_ratio: row['COMPRESSION RATIO'],
    engine_power: row['ENGINE POWER'],
    cylinder_diameter: row['CYLINDER DIAMETER'],
    piston_compression_height: row['PISTON COMPRESSION HEIGHT'],
    piston_bowl_diameter: row['PISTON BOWL DIAMETER'],
    piston_bowl_depth: row['PISTON BOWL DEPTH'],
    piston_bowl_offset: row['PISTON BOWL OFF-SET'],
    top_land_width: row['TOP LAND WIDTH'],
    pin_boss_spacing: row['PIN BOSS SPACING'],
    dome_height: row['DOME HEIGHT'],
    valve_recess_depth: row['VALVE RECESS DEPTH'],
    piston_pin_outside_diameter: row['PISTON PIN OUTSIDE DIAMETER'],
    total_piston_length: row['TOTAL PISTON LENGTH'],
    piston_ring_dimensions: row['PISTON RING DIMENSIONS'],
    aluminum_piston_cast_no: row['ALUMINUM PISTON CAST NO'],
    articulated_piston_crown_cast_no: row['ARTICULATED PISTON CROWN CAST NO'],
    articulated_piston_skirt_cast_no: row['ARTICULATED PISTON SKIRT CAST NO'],
    drt_kk_ak_ha_nb: row['(D)RT / KK / AK / HA / NB etc.'],
    earlier_piston_equivalent_reference_numbers: row['EARLIER PISTON EQUIVALENT REFERENCE NUMBERS'],
    other_makers_piston_reference_numbers: row['OTHER MAKERS PISTON REFERENCE NUMBERS'],
    genuine_oe_reference_no: row['GENUINE OE REFERENCE NO'],
    mahle_ref_no: row['MAHLE / KS / AE / OE ASS REF. No.'],
    ae: row['AE'],
    af: row['AF'],
    mahle_liner_ref_no: row['MAHLE / KS / AE / OE LINER REF. No.'],
    ah: row['AH'],
    ai: row['AI'],
    liner_flange_diameter: row['LINER FLANGE DIAMETER'],
    liner_flange_height: row['LINER FLANGE HEIGHT'],
    liner_fire_wall_height: row['LINER FIRE WALL HEIGHT'],
    liner_diameter_at_seals: row['LINER DIAMETER AT SEALS'],
    total_liner_length: row['TOTAL LINER LENGTH'],
    liner_pin_bore_relief_height: row['LINER PIN BORE RELIEF HEIGHT'],
    liner_fire_ring: row['LINER FIRE RING'],
  )
end